"""replace file_url with storage path

Revision ID: 5b6b353af162
Revises: a2defd23efc6
Create Date: 2026-02-15 14:44:18.361865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b6b353af162'
down_revision: Union[str, Sequence[str], None] = 'a2defd23efc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.add_column(
        "uploads",
        sa.Column("storage_path", sa.String(length=500), nullable=True),
    )

    # copy data
    op.execute(
        "UPDATE uploads SET storage_path = file_url"
    )

    # make NOT NULL
    op.alter_column(
        "uploads",
        "storage_path",
        nullable=False,
    )

    op.drop_column("uploads", "file_url")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploads', sa.Column('file_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.drop_column('uploads', 'storage_path')
    # ### end Alembic commands ###
