"""add form field unique constraint

Revision ID: a2defd23efc6
Revises: a6b7d42bfc46
Create Date: 2026-02-15 12:50:47.721172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2defd23efc6'
down_revision: Union[str, Sequence[str], None] = 'a6b7d42bfc46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_field_per_internship', 'internship_form_fields', ['internship_id', 'field_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_field_per_internship', 'internship_form_fields', type_='unique')
    # ### end Alembic commands ###
